# Generated by Django 5.0.4 on 2024-04-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corp_print_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temlate',
            new_name='Template',
        ),
    ]
