# Generated by Django 5.0.4 on 2024-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corp_print_app', '0005_profile_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('background_image', models.ImageField(upload_to='corp_print_app/media/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='corp_print_app/media/')),
                ('text', models.TextField(blank=True, null=True)),
                ('font', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
